In [1]:
import pandas as pd

# 데이터 불러오기

In [37]:
car_data = pd.read_excel("C:\\Users\\owner\\PythonWork\\Final_project\\차량별 부품가격.xlsx")

In [38]:
car_data

,제조사,차이름,차량크기,연식,Bumper,Bonnet,Roof,Head lights,Front door,Rear door,Front Fender,Rocker panel,Side mirror,Rear Fender,Trunk lid,Rear Bumper,Rear lamp,Wheel
0,기아,모닝,경형,8,63000,147000,137000,79000,165000,145000,51000,110000,11000,127000,140000,63000,46000,145000
1,기아,모닝,경형,11,67000,158000,137000,81000,187000,167000,50000,215000,36000,200000,125000,67000,39000,120000
2,기아,모닝,경형,15,67000,158000,137000,81000,187000,167000,50000,215000,37000,200000,125000,68000,39000,108000
3,기아,모닝,경형,17,67000,160000,137000,109000,187000,154000,50000,187000,39000,220000,164000,63000,52000,140000
4,기아,모닝,경형,20,69000,160000,137000,109000,187000,154000,50000,187000,39000,226000,164000,68000,52000,126000
5,기아,k3,소형,12,120000,286000,150000,130000,300000,310000,90000,180000,94000,308000,300000,120000,110000,114000
6,기아,k3,소형,16,120000,286000,150000,130000,390000,310000,90000,180000,94000,308000,300000,120000,120000,114000
7,기아,k3,소형,18,110000,420000,170000,310000,390000,330000,90000,167000,120000,280000,324000,120000,120000,125000
8,기아,k3,소형,21,130000,420000,170000,450000,390000,400000,90000,167000,120000,280000,324000,120000,120000,150000
9,기아,k5,중형,11,126000,410000,180000,130000,336000,330000,88000,290000,88000,250000,370000,166000,140000,120000
10,기아,k5,중형,14,116000,337000,180000,277000,336000,330000,88000,290000,127000,250000,310000,166000,130000,120000
11,기아,k5,중형,16,140000,337000,170000,335000,336000,330000,88000,235000,110000,330000,338000,164000,121000,150000
12,기아,k5,중형,18,140000,337000,170000,370000,336000,330000,88000,235000,110000,330000,338000,164000,121000,137000
13,기아,k5,중형,20,140000,360000,170000,410000,383000,369000,115000,235000,120000,340000,279000,143000,146000,120000
14,기아,k7,대형,8,125000,416000,179000,433000,422000,347000,110000,288000,140000,330000,339000,154000,130000,124000
15,기아,k7,대형,13,130000,416000,179000,500000,422000,369000,110000,288000,134000,330000,339000,157000,159000,137000
16,기아,k7,대형,16,155000,416000,179000,497000,422000,403000,132000,250000,134000,346000,398000,173000,152000,175000
17,기아,k7,대형,19,155000,416000,179000,649000,422000,403000,132000,250000,200000,346000,398000,173000,155000,196000
18,기아,k9,대형,11,133000,446000,205000,1235000,422000,336000,132000,544000,152000,484000,339000,157000,251000,160000
19,기아,k9,대형,15,133000,446000,205000,123500,422000,404000,132000,545000,172000,484000,339000,157000,234000,220000
20,기아,k9,대형,18,133000,430000,223000,892000,422000,336000,169000,256000,332000,573000,339000,112000,394000,111000
21,기아,카니발,승합,14,122000,240000,248000,170000,280000,258000,110000,300000,124000,380000,440000,102000,160000,150000
22,기아,카니발,승합,18,130000,240000,248000,170000,280000,258000,110000,300000,124000,380000,440000,102000,160000,150000
23,기아,카니발,승합,20,130000,240000,248000,440000,3190000,258000,990000,300000,130000,380000,390000,102000,160000,198000
24,현대,투싼,SUV,10,78000,268000,175000,118000,276000,275000,76000,159000,66000,288000,230000,89000,48000,125000
25,현대,투싼,SUV,14,78000,268000,175000,190000,276000,275000,76000,159000,72000,288000,230000,89000,48000,168000
26,현대,투싼,SUV,15,76000,268000,175000,250000,294000,256000,83000,159000,136000,382000,230000,76000,59000,159000
27,현대,투싼,SUV,18,84000,268000,175000,179000,294000,256000,83000,159000,136000,382000,230000,760000,59000,169000
28,기아,쏘렌토,SUV,12,124000,323000,218000,615000,530000,325000,99000,170000,117000,325000,367000,143000,143000,164000
29,기아,쏘렌토,SUV,15,117000,323000,264000,610000,369000,336000,99000,210000,121000,383000,341000,134000,176000,155000
30,기아,쏘렌토,SUV,18,117000,323000,264000,728000,369000,336000,99000,210000,121000,383000,367000,134000,176000,189000
31,기아,쏘렌토,SUV,20,119000,323000,264000,610000,369000,336000,141000,170000,121000,383000,367000,134000,266000,250000
32,현대,제네시스G80,대형,16,133000,550000,245000,890000,363000,485000,143000,496000,135000,481000,315000,146000,246000,288000
33,현대,제네시스G80,대형,20,176000,550000,245000,890000,533000,320000,167000,256000,222000,573000,484000,155000,270000,313000
34,현대,그랜저11,대형,11,156000,416000,145000,344000,169000,113000,121000,450000,110000,378000,316000,173000,148000,114000
35,현대,그랜저15,대형,15,156000,416000,154000,302000,169000,113000,121000,450000,110000,378000,316000,173000,148000,182000
36,현대,그랜저17,대형,17,143000,410000,176000,740000,252000,141000,121000,250000,140000,403000,288000,132000,173000,183000
37,현대,그랜저19,대형,19,143000,410000,176000,740000,252000,198000,157000,250000,140000,403000,288000,132000,210000,196000
38,현대,아반떼,소형,11,96700,210000,149000,366000,237000,209000,75000,168000,307000,303000,263000,102000,131000,120000
39,현대,아반떼,소형,14,101000,210000,149000,363000,259000,231000,75000,168000,307000,303000,263000,102000,154000,120000
40,현대,아반떼,소형,16,97000,286000,166000,366000,330000,310000,168000,150000,126000,308000,263000,102000,154000,134000
41,현대,아반떼,소형,20,100000,290000,166000,366000,330000,381000,176000,150000,121000,308000,303000,107000,165000,126000
42,현대,소나타,중형,10,140000,308000,157000,132000,301000,313000,88000,207000,50000,240000,263000,166000,132000,121000
43,현대,소나타,중형,14,141000,390000,170000,181000,301000,313000,88000,296000,113000,334000,279000,164000,70600,154000
44,현대,소나타,중형,17,119000,390000,170000,517000,301000,370000,88000,296000,113000,334000,279000,164000,109000,123000
45,현대,소나타,중형,19,141000,390000,157300,585000,301000,385000,165000,235000,160000,343000,279000,155000,134000,121000
46,현대,코나,중형,19,146000,323000,175000,237600,327000,313000,80000,159000,111000,352000,207000,113000,90000,154000
47,현대,코나,중형,21,146000,323000,175000,152000,320000,313000,80000,159000,111000,352000,207000,95000,90000,154000
48,현대,코나,중형,23,143000,323000,175000,258000,248000,231000,80000,159000,117000,352000,246000,130000,120000,157000
49,기아,샐토스,중형,19,146000,323000,176000,343000,248000,231000,80000,198000,110000,352000,246000,105000,158000,149000
50,기아,샐토스,중형,23,146000,323000,176000,343000,248000,231000,80000,198000,110000,352000,246000,105000,158000,149000
51,기아,레이,경형,11,77000,147000,242000,218000,187000,176000,52000,168000,96000,219000,191000,66000,159000,130000
52,기아,레이,경형,23,77000,147000,240000,179000,165000,170000,62000,168000,96000,219000,191000,77000,150000,126000
53,삼성,qm3,소형,22,115000,260000,187000,207000,163000,155000,76000,200000,110000,72500,160000,114000,154000,160000
54,현대,제네시스GV70,SUV,21,130000,350000,264000,930000,350000,290000,142000,270000,285000,380000,420000,132000,196000,258000
55,현대,제네시스GV80,SUV,20,140000,385000,264000,923000,450000,452000,165000,271000,270000,440000,456000,121000,160000,432000

In [39]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   제조사           56 non-null     object
 1   차이름           56 non-null     object
 2   차량크기          56 non-null     object
 3   연식            56 non-null     int64
 4   Bumper        56 non-null     int64
 5   Bonnet        56 non-null     int64
 6   Roof          56 non-null     int64
 7   Head lights   56 non-null     int64
 8   Front door    56 non-null     int64
 9   Rear door     56 non-null     int64
 10  Front Fender  56 non-null     int64
 11  Rocker panel  56 non-null     int64
 12  Side mirror   56 non-null     int64
 13  Rear Fender   56 non-null     int64
 14  Trunk lid     56 non-null     int64
 15  Rear Bumper   56 non-null     int64
 16  Rear lamp     56 non-null     int64
 17  Wheel         56 non-null     int64
dtypes: int64(15), object(3)
memory usage: 8.0+ KB

# sql 연결

In [2]:
import pymysql

In [41]:
conn = pymysql.connect(host='localhost', user='root', password='1111', db='final_project')
curs = conn.cursor(pymysql.cursors.DictCursor)

In [42]:
for column in car_data.columns:
    if car_data[column].dtype == 'object' and car_data[column].apply(lambda x: isinstance(x, str)).all():
        car_data[column] = car_data[column].str.encode('utf-8').str.decode('utf-8')

print(car_data['제조사'].unique())

['기아' '현대' '삼성']

In [43]:
manufacturer = car_data.loc[idx, '제조사'].encode('utf-8')
manufacturer = car_data.loc[idx, '차이름'].encode('utf-8')
manufacturer = car_data.loc[idx, '차량크기'].encode('utf-8')

In [54]:
import pymysql

# MySQL 연결 정보
host = 'localhost'  # 호스트
user = 'root'  # 사용자명
password = '1111'  # 비밀번호
database = 'final_project'  # 데이터베이스 이름

# 데이터베이스 연결
conn = pymysql.connect(host=host, user=user, password=password, database=database)
curs = conn.cursor(pymysql.cursors.DictCursor)

# 테이블 생성
create_table_sql = """
CREATE TABLE car_data2 (
    제조사 VARCHAR(200) CHARACTER SET utf8,
    차이름 VARCHAR(200) CHARACTER SET utf8,
    차량크기 VARCHAR(200) CHARACTER SET utf8,
    연식 VARCHAR(200) CHARACTER SET utf8,
    Bumper VARCHAR(200) CHARACTER SET utf8,
    Bonnet VARCHAR(200) CHARACTER SET utf8,
    Roof VARCHAR(200) CHARACTER SET utf8,
    `Head lights` VARCHAR(200) CHARACTER SET utf8,
    `Front door` VARCHAR(200) CHARACTER SET utf8,
    `Rear door` VARCHAR(200) CHARACTER SET utf8,
    `Front Fender` VARCHAR(200) CHARACTER SET utf8,
    `Rocker panel` VARCHAR(200) CHARACTER SET utf8,
    `Side mirror` VARCHAR(200) CHARACTER SET utf8,
    `Rear Fender` VARCHAR(200) CHARACTER SET utf8,
    `Trunk lid` VARCHAR(200) CHARACTER SET utf8,
    `Rear Bumper` VARCHAR(200) CHARACTER SET utf8,
    `Rear lamp` VARCHAR(200) CHARACTER SET utf8,
    Wheel VARCHAR(200) CHARACTER SET utf8
)
"""

curs.execute(create_table_sql)
conn.commit()

# 데이터 삽입
sql = """
INSERT INTO car_data2 (제조사, 차이름, 차량크기, 연식, Bumper, Bonnet, Roof, `Head lights`, `Front door`, `Rear door`,
    `Front Fender`, `Rocker panel`, `Side mirror`, `Rear Fender`, `Trunk lid`, `Rear Bumper`, `Rear lamp`, Wheel)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

for idx in range(len(car_data)):
    curs.execute(sql, (
        str(car_data.loc[idx, '제조사']),
        str(car_data.loc[idx, '차이름']),
        str(car_data.loc[idx, '차량크기']),
        str(car_data.loc[idx, '연식']),
        str(car_data.loc[idx, 'Bumper']),
        str(car_data.loc[idx, 'Bonnet']),
        str(car_data.loc[idx, 'Roof']),
        str(car_data.loc[idx, 'Head lights']),
        str(car_data.loc[idx, 'Front door']),
        str(car_data.loc[idx, 'Rear door']),
        str(car_data.loc[idx, 'Front Fender']),
        str(car_data.loc[idx, 'Rocker panel']),
        str(car_data.loc[idx, 'Side mirror']),
        str(car_data.loc[idx, 'Rear Fender']),
        str(car_data.loc[idx, 'Trunk lid']),
        str(car_data.loc[idx, 'Rear Bumper']),
        str(car_data.loc[idx, 'Rear lamp']),
        str(car_data.loc[idx, 'Wheel'])
    ))

# 변경사항을 커밋
conn.commit()

# 연결 종료
conn.close()

# 차량 크기별 도장가격 파일 불러오기

In [56]:
car_coating_price = pd.read_excel("C:\\Users\\owner\\PythonWork\\Final_project\\크기별 도장가격.xlsx")

In [57]:
car_coating_price

,차량크기,Bumper,Bonnet,Roof,Head lights,Front door,Rear door,Front Fender,Rocker panel,Side mirror,Rear Fender,Trunk lid,Rear Bumper,Rear lamp,Wheel
0,경형,40100,37000,30800,0,31000,31000,33100,32340,0,30000,41200,38500,0,0
1,소형,47320,43680,36400,0,35945,36400,39130,38220,0,33670,48685,45500,0,0
2,중형,52000,48000,40000,0,39500,40000,43000,42000,0,37000,53500,50000,0,0
3,대형,56000,515000,44000,0,42500,43500,51000,44000,0,39500,43800,52500,0,0
4,SUV,55300,50800,44000,0,47800,43700,47700,44000,0,38700,43700,55700,0,0
5,VAN,56000,52000,44000,0,56000,44000,48000,44000,0,38000,43000,57000,0,0

# sql에 db 입력

In [58]:
conn = pymysql.connect(host='localhost', user='root', password='1111', db='final_project')
curs = conn.cursor(pymysql.cursors.DictCursor)

In [65]:
# MySQL 연결 정보
host = 'localhost'  # 호스트
user = 'root'  # 사용자명
password = '1111'  # 비밀번호
database = 'final_project'  # 데이터베이스 이름

# 데이터베이스 연결
conn = pymysql.connect(host=host, user=user, password=password, database=database)
curs = conn.cursor(pymysql.cursors.DictCursor)

# # 테이블 생성
# create_table_sql = """
# CREATE TABLE car_coating_price (
#     차량크기 VARCHAR(200) CHARACTER SET utf8,    
#     Bumper VARCHAR(200) CHARACTER SET utf8,
#     Bonnet VARCHAR(200) CHARACTER SET utf8,
#     Roof VARCHAR(200) CHARACTER SET utf8,
#     `Head lights` VARCHAR(200) CHARACTER SET utf8,
#     `Front door` VARCHAR(200) CHARACTER SET utf8,
#     `Rear door` VARCHAR(200) CHARACTER SET utf8,
#     `Front Fender` VARCHAR(200) CHARACTER SET utf8,
#     `Rocker panel` VARCHAR(200) CHARACTER SET utf8,
#     `Side mirror` VARCHAR(200) CHARACTER SET utf8,
#     `Rear Fender` VARCHAR(200) CHARACTER SET utf8,
#     `Trunk lid` VARCHAR(200) CHARACTER SET utf8,
#     `Rear Bumper` VARCHAR(200) CHARACTER SET utf8,
#     `Rear lamp` VARCHAR(200) CHARACTER SET utf8,
#     Wheel VARCHAR(200) CHARACTER SET utf8
# )
# """

# curs.execute(create_table_sql)
# conn.commit()

# 데이터 삽입
sql = """
INSERT INTO car_coating_price (차량크기, Bumper, Bonnet, Roof, `Head lights`, `Front door`, `Rear door`,
    `Front Fender`, `Rocker panel`, `Side mirror`, `Rear Fender`, `Trunk lid`, `Rear Bumper`, `Rear lamp`, Wheel)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

for idx in range(len(car_coating_price)):
    curs.execute(sql, (
        str(car_coating_price.loc[idx, '차량크기']),
        str(car_coating_price.loc[idx, 'Bumper']),
        str(car_coating_price.loc[idx, 'Bonnet']),
        str(car_coating_price.loc[idx, 'Roof']),
        str(car_coating_price.loc[idx, 'Head lights']),
        str(car_coating_price.loc[idx, 'Front door']),
        str(car_coating_price.loc[idx, 'Rear door']),
        str(car_coating_price.loc[idx, 'Front Fender']),
        str(car_coating_price.loc[idx, 'Rocker panel']),
        str(car_coating_price.loc[idx, 'Side mirror']),
        str(car_coating_price.loc[idx, 'Rear Fender']),
        str(car_coating_price.loc[idx, 'Trunk lid']),
        str(car_coating_price.loc[idx, 'Rear Bumper']),
        str(car_coating_price.loc[idx, 'Rear lamp']),
        str(car_coating_price.loc[idx, 'Wheel'])
))
    

# 변경사항을 커밋
conn.commit()

# 연결 종료
conn.close()

## 차량 색상 불러오기 및 DB에 넣기

In [4]:
car_color = pd.read_excel("C:\\Users\\owner\\PythonWork\\Final_project\\색상가격배율0704.xlsx")

In [5]:
car_color

   색상명  1LT 기준  화이트대비
0  화이트   68000    1.0
1   레드  136000    2.0
2  오렌지  128000    1.9
3  그레이   84800    1.2
4   블루  110000    1.6
5   실버   73000    1.1
6   블랙   60000    0.9

In [14]:
# MySQL 연결 정보
host = 'localhost'  # 호스트
user = 'root'  # 사용자명
password = '1111'  # 비밀번호
database = 'final_project'  # 데이터베이스 이름

# 데이터베이스 연결
conn = pymysql.connect(host=host, user=user, password=password, database=database)
curs = conn.cursor(pymysql.cursors.DictCursor)

# create_table_sql = """
# CREATE TABLE car_color_price (
#      color VARCHAR(200) CHARACTER SET utf8,    
#     `price 1L` VARCHAR(200) CHARACTER SET utf8,
#     `white contrast` VARCHAR(200) CHARACTER SET utf8
# )
# """


# curs.execute(create_table_sql)
# conn.commit()

sql = """
INSERT INTO car_color_price(color, `price 1L`, `white contrast`)
VALUES (%s, %s, %s)
"""



for idx in range(len(car_color)):
    curs.execute(sql, (
        str(car_color.loc[idx, '색상명']),
        str(car_color.loc[idx, '1LT 기준']),
        str(car_color.loc[idx, '화이트대비'])
))

conn.commit()
conn.close()